import { Category, Product, Service } from './types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'All Products', slug: 'all', display_order: 0 },
  { id: 'cat-2', name: 'Solar Panels & Inverters', slug: 'solar-panels-inverters', description: 'High-efficiency Tier-1 monocrystalline solar panels and hybrid pure sine wave inverters.', display_order: 1 },
  { id: 'cat-3', name: 'Batteries & Charge Controllers', slug: 'solar-batteries-controllers', description: 'Deep cycle gel batteries, LiFePO4 lithium storage packs, and MPPT controllers.', display_order: 2 },
  { id: 'cat-4', name: 'Professional Speakers & PA Systems', slug: 'pro-speakers-pa', description: 'Commercial loudspeakers, stage monitors, subwoofers, and PA line arrays.', display_order: 3 },
  { id: 'cat-5', name: 'Amplifiers & Audio Mixers', slug: 'amplifiers-audio', description: 'High-power audio amplifiers, multi-channel sound mixers, and wireless mic systems.', display_order: 4 },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    category_id: 'cat-2',
    category: MOCK_CATEGORIES[1],
    name: 'Jinko 550W N-Type Monocrystalline Solar Panel',
    slug: 'jinko-550w-n-type-monocrystalline-solar-panel',
    sku: 'SEB-SLR-550',
    price: 18500,
    currency: 'ETB',
    description: 'Tier-1 ultra-high efficiency N-type TOPCon monocrystalline solar module. Built with anti-reflective tempered glass, corrosion-resistant anodized aluminum frame, and 22.5% module conversion efficiency for harsh climatic conditions.',
    details: {
      brand: 'Jinko Solar / Sebrin Certified',
      power_output: '550 Watts Peak (STC)',
      voltage: '41.95V (Vmp) / 50.10V (Voc)',
      dimensions: '2278 x 1134 x 35 mm',
      weight: '28.0 kg',
      warranty: '12-Year Product / 30-Year Power Output Warranty',
    },
    is_featured: true,
    is_visible: true,
    stock_status: 'in_stock',
    created_at: '2026-08-01T10:00:00Z',
    images: [
      {
        id: 'img-1a',
        product_id: 'prod-1',
        url: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?q=80&w=1000&auto=format&fit=crop',
        alt_text: 'Jinko 550W Solar Panel Front View',
        is_primary: true,
        display_order: 0,
      },
      {
        id: 'img-1b',
        product_id: 'prod-1',
        url: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?q=80&w=1000&auto=format&fit=crop',
        alt_text: 'Rooftop Solar Installation Detail',
        is_primary: false,
        display_order: 1,
      },
    ],
  },
  {
    id: 'prod-2',
    category_id: 'cat-2',
    category: MOCK_CATEGORIES[1],
    name: 'Must 5.5kW Hybrid Pure Sine Wave Solar Inverter (48V)',
    slug: 'must-55kw-hybrid-pure-sine-wave-solar-inverter-48v',
    sku: 'SEB-INV-5500',
    price: 95000,
    currency: 'ETB',
    description: 'Multi-function 5500W 48V hybrid inverter combining functions of pure sine wave inverter, 100A MPPT solar charge controller, and utility battery charger. Features LCD display configuration and dual AC outputs.',
    details: {
      brand: 'Must Power Systems',
      power_output: '5500W Continuous / 11000W Surge',
      voltage: '48VDC Input / 230VAC Output',
      frequency_response: '50Hz / 60Hz Pure Sine Wave',
      dimensions: '468 x 330 x 119 mm',
      warranty: '2-Year Full Manufacturer Warranty',
    },
    is_featured: true,
    is_visible: true,
    stock_status: 'in_stock',
    created_at: '2026-08-02T12:00:00Z',
    images: [
      {
        id: 'img-2a',
        product_id: 'prod-2',
        url: 'https://images.unsplash.com/photo-1613665813446-82a78c468a1d?q=80&w=1000&auto=format&fit=crop',
        alt_text: 'Hybrid Solar Inverter',
        is_primary: true,
        display_order: 0,
      },
    ],
  },
  {
    id: 'prod-3',
    category_id: 'cat-3',
    category: MOCK_CATEGORIES[2],
    name: 'Felicity 51.2V 100Ah 5kWh LiFePO4 Lithium Battery Pack',
    slug: 'felicity-512v-100ah-5kwh-lifepo4-lithium-battery-pack',
    sku: 'SEB-BAT-5KWH',
    price: 165000,
    currency: 'ETB',
    description: 'Wall-mounted 5.12kWh Lithium Iron Phosphate (LiFePO4) solar energy storage pack. Built-in smart BMS protection, over 6,000 deep discharge cycles at 80% DOD, and parallel scalability up to 15 units.',
    details: {
      brand: 'Felicity Solar / Sebrin Storage',
      capacity: '100Ah / 5.12 kWh Usable Energy',
      voltage: '51.2V Nominal (44.8V - 57.6V Range)',
      weight: '48 kg',
      warranty: '5-Year Manufacturer Warranty / 6000+ Cycles',
    },
    is_featured: true,
    is_visible: true,
    stock_status: 'in_stock',
    created_at: '2026-08-03T14:00:00Z',
    images: [
      {
        id: 'img-3a',
        product_id: 'prod-3',
        url: 'https://images.unsplash.com/photo-1548337138-e87d889cc369?q=80&w=1000&auto=format&fit=crop',
        alt_text: 'Lithium LiFePO4 Battery Storage Unit',
        is_primary: true,
        display_order: 0,
      },
    ],
  },
  {
    id: 'prod-4',
    category_id: 'cat-3',
    category: MOCK_CATEGORIES[2],
    name: 'Sebrin Power 200Ah 12V Maintenance-Free Gel Deep Cycle Battery',
    slug: 'sebrin-power-200ah-12v-maintenance-free-gel-deep-cycle-battery',
    sku: 'SEB-BAT-200GEL',
    price: 38000,
    currency: 'ETB',
    description: 'Heavy-duty 12V 200Ah valve-regulated sealed lead-gel battery for solar backup and UPS systems. Features thick lead-calcium grid alloy plates for deep discharge recovery and long standby service life.',
    details: {
      brand: 'Sebrin Power Tech',
      capacity: '200Ah @ 10-Hour Rate',
      voltage: '12V Nominal',
      dimensions: '522 x 240 x 219 mm',
      weight: '59 kg',
      warranty: '2-Year Replacement Guarantee',
    },
    is_featured: false,
    is_visible: true,
    stock_status: 'in_stock',
    created_at: '2026-08-04T09:00:00Z',
    images: [
      {
        id: 'img-4a',
        product_id: 'prod-4',
        url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?q=80&w=1000&auto=format&fit=crop',
        alt_text: '200Ah 12V Gel Solar Battery',
        is_primary: true,
        display_order: 0,
      },
    ],
  },
  {
    id: 'prod-5',
    category_id: 'cat-4',
    category: MOCK_CATEGORIES[3],
    name: 'JBL SRX835P 15" 3-Way Powered Professional Loudspeaker (2000W)',
    slug: 'jbl-srx835p-15-3-way-powered-professional-loudspeaker-2000w',
    sku: 'SEB-SPK-835P',
    price: 185000,
    currency: 'ETB',
    description: 'Premium 15-inch 3-way powered sound reinforcement speaker equipped with Crown Class-D amplification (2000W Peak). Features full HiQnet network control, onboard 400MHz Sharc DSP, and Duraflex wooden enclosure for concerts and auditoriums.',
    details: {
      brand: 'JBL Professional / Sebrin Audio',
      power_output: '2000W Peak / 1500W Continuous Class-D',
      frequency_response: '33Hz - 21kHz (-10dB)',
      impedance: 'Active Powered System',
      dimensions: '476 x 544 x 984 mm',
      weight: '38.6 kg',
      warranty: '3-Year JBL Manufacturer Warranty',
    },
    is_featured: true,
    is_visible: true,
    stock_status: 'in_stock',
    created_at: '2026-08-05T08:00:00Z',
    images: [
      {
        id: 'img-5a',
        product_id: 'prod-5',
        url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=1000&auto=format&fit=crop',
        alt_text: 'Professional Concert Stage Loudspeaker',
        is_primary: true,
        display_order: 0,
      },
      {
        id: 'img-5b',
        product_id: 'prod-5',
        url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1000&auto=format&fit=crop',
        alt_text: 'Stage Audio Setup View',
        is_primary: false,
        display_order: 1,
      },
    ],
  },
  {
    id: 'prod-6',
    category_id: 'cat-5',
    category: MOCK_CATEGORIES[4],
    name: 'Yamaha EMX5016CF 16-Channel 1000W Powered Audio Mixer',
    slug: 'yamaha-emx5016cf-16-channel-1000w-powered-audio-mixer',
    sku: 'SEB-MIX-5016',
    price: 125000,
    currency: 'ETB',
    description: 'High-performance 16-input powered audio console with 500W + 500W stereo amplifier. Built-in dual SPX digital multi-effects processors, 9-band digital graphic EQ with preset recall, and Maximizer loudness booster.',
    details: {
      brand: 'Yamaha Commercial Audio',
      power_output: '500W + 500W @ 4Ω (1000W Total)',
      frequency_response: '20Hz - 20kHz (+0.5dB, -1.5dB)',
      dimensions: '444 x 155 x 493 mm',
      weight: '11.0 kg',
      warranty: '2-Year Yamaha Warranty',
    },
    is_featured: true,
    is_visible: true,
    stock_status: 'in_stock',
    created_at: '2026-08-05T10:00:00Z',
    images: [
      {
        id: 'img-6a',
        product_id: 'prod-6',
        url: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=1000&auto=format&fit=crop',
        alt_text: '16-Channel Audio Mixing Console',
        is_primary: true,
        display_order: 0,
      },
    ],
  },
  {
    id: 'prod-7',
    category_id: 'cat-5',
    category: MOCK_CATEGORIES[4],
    name: 'Shure BLX288/PG58 Dual Wireless Handheld Microphone System',
    slug: 'shure-blx288pg58-dual-wireless-handheld-microphone-system',
    sku: 'SEB-MIC-BLX288',
    price: 52000,
    currency: 'ETB',
    description: 'Dual channel wireless system with two PG58 handheld dynamic microphone transmitters. One-touch QuickScan frequency selection for interference-free wireless transmission up to 300 feet range.',
    details: {
      brand: 'Shure Audio Tech',
      frequency_response: '50Hz - 15kHz Dynamic Capsule',
      voltage: '12V - 15V DC Power Supply Included',
      warranty: '2-Year Manufacturer Warranty',
    },
    is_featured: false,
    is_visible: true,
    stock_status: 'in_stock',
    created_at: '2026-08-05T11:00:00Z',
    images: [
      {
        id: 'img-7a',
        product_id: 'prod-7',
        url: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?q=80&w=1000&auto=format&fit=crop',
        alt_text: 'Wireless Stage Microphone System',
        is_primary: true,
        display_order: 0,
      },
    ],
  },
  {
    id: 'prod-8',
    category_id: 'cat-3',
    category: MOCK_CATEGORIES[2],
    name: '60A MPPT Solar Charge Controller (12V / 24V / 48V Auto)',
    slug: '60a-mppt-solar-charge-controller-12v-24v-48v-auto',
    sku: 'SEB-MPPT-60A',
    price: 19500,
    currency: 'ETB',
    description: 'Advanced Maximum Power Point Tracking (MPPT) solar charge controller with 98% tracking efficiency. Backlit LCD screen displays charging current, PV voltage, and battery temperature compensation status.',
    details: {
      brand: 'Sebrin Solar Tech',
      voltage: '12V / 24V / 36V / 48V Auto Recognition',
      power_output: '60A Max Charging Current (PV Input up to 150V)',
      warranty: '2-Year Replacement Warranty',
    },
    is_featured: false,
    is_visible: true,
    stock_status: 'in_stock',
    created_at: '2026-08-05T12:00:00Z',
    images: [
      {
        id: 'img-8a',
        product_id: 'prod-8',
        url: 'https://images.unsplash.com/photo-1558441719-674508053d56?q=80&w=1000&auto=format&fit=crop',
        alt_text: 'MPPT Solar Charge Controller',
        is_primary: true,
        display_order: 0,
      },
    ],
  },
  {
    id: 'prod-pkg-1',
    category_id: 'cat-2',
    category: MOCK_CATEGORIES[1],
    name: 'Essential Solar Backup Package (3.5kW)',
    slug: 'essential-solar-backup-package',
    sku: 'SEB-PKG-ESS',
    price: 180000,
    currency: 'ETB',
    description: 'Essential daytime & evening backup with automatic power transfer. Ideal for small homes and vital appliances.',
    details: {
      brand: 'Sebrin Kits',
    },
    is_featured: true,
    is_visible: true,
    stock_status: 'in_stock',
    created_at: '2026-08-06T12:00:00Z',
    images: [],
    solar_attributes: [{
      id: 'sa-1',
      product_id: 'prod-pkg-1',
      product_type: 'package_kit',
      wattage_wp: 1100,
      inverter_kva: 3.5,
      battery_capacity_kwh: 2.56,
      min_kw_load: 0.5,
      max_kw_load: 2.5,
    }]
  },
  {
    id: 'prod-pkg-2',
    category_id: 'cat-2',
    category: MOCK_CATEGORIES[1],
    name: 'Full Household Hybrid Solar Kit (5.5kW)',
    slug: 'full-household-hybrid-solar-kit',
    sku: 'SEB-PKG-REC',
    price: 310000,
    currency: 'ETB',
    description: '24/7 uninterrupted power for standard villas. Includes high-efficiency Tier-1 TOPCon solar panels and LiFePO4 battery.',
    details: {
      brand: 'Sebrin Kits',
    },
    is_featured: true,
    is_visible: true,
    stock_status: 'in_stock',
    created_at: '2026-08-06T12:00:00Z',
    images: [],
    solar_attributes: [{
      id: 'sa-2',
      product_id: 'prod-pkg-2',
      product_type: 'package_kit',
      wattage_wp: 2200,
      inverter_kva: 5.5,
      battery_capacity_kwh: 5.12,
      min_kw_load: 2.6,
      max_kw_load: 5.0,
    }]
  },
  {
    id: 'prod-pkg-3',
    category_id: 'cat-2',
    category: MOCK_CATEGORIES[1],
    name: 'Heavy-Duty Commercial / Off-Grid Master Kit (11kW)',
    slug: 'heavy-duty-commercial-off-grid-master-kit',
    sku: 'SEB-PKG-PRO',
    price: 650000,
    currency: 'ETB',
    description: 'Extended multi-day rainy weather autonomy. High surge capacity for AC & commercial pumps.',
    details: {
      brand: 'Sebrin Kits',
    },
    is_featured: true,
    is_visible: true,
    stock_status: 'in_stock',
    created_at: '2026-08-06T12:00:00Z',
    images: [],
    solar_attributes: [{
      id: 'sa-3',
      product_id: 'prod-pkg-3',
      product_type: 'package_kit',
      wattage_wp: 4400,
      inverter_kva: 11.0,
      battery_capacity_kwh: 10.24,
      min_kw_load: 5.1,
      max_kw_load: 15.0,
    }]
  }
];

export const MOCK_SERVICES: Service[] = [
  {
    id: 'srv-1',
    title: 'Turnkey Solar Power System Sizing & Installation',
    slug: 'turnkey-solar-power-system-sizing-installation',
    subtitle: 'Commercial, industrial & residential solar design from roof assessment to inverter commissioning.',
    description: 'Sebrin Trading PLC provides full technical assessment, load calculation, solar array mounting, high-capacity inverter configuration, and lithium battery storage installation for uninterrupted power supply across Ethiopia.',
    specifications: [
      'Site Load & Solar Irradiance Analysis',
      'Tier-1 Monocrystalline Panel Mounting & Cable Management',
      'Hybrid Inverter & Lithium Battery Commissioning',
      'Surge Protection & Safety Disconnect Installation',
    ],
    price_range: 'Custom Quote',
    is_active: true,
    display_order: 1,
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'srv-2',
    title: 'Commercial Sound System & Acoustic Engineering Setup',
    slug: 'commercial-sound-system-acoustic-engineering-setup',
    subtitle: 'Professional audio system installation for auditoriums, churches, venues, and commercial spaces.',
    description: 'End-to-end sound system design including loudspeaker placement modeling, active mixer tuning, UHF wireless microphone distribution, and power amplifier impedance matching for crystal-clear acoustics.',
    specifications: [
      'Venue Acoustic Measurement & Speaker Placement Modeling',
      'Powered Speaker & Subwoofer Array Tuning',
      'Multi-Channel Audio Console & DSP Equalization Calibration',
      'Wireless UHF Microphone Frequency Scan & Installation',
    ],
    price_range: 'Custom Quote',
    is_active: true,
    display_order: 2,
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'srv-3',
    title: 'Solar Battery Bank & Inverter Maintenance & Upgrades',
    slug: 'solar-battery-bank-inverter-maintenance-upgrades',
    subtitle: 'Preventative maintenance, battery health diagnostics, and capacity upgrades for existing solar systems.',
    description: 'Diagnose degraded battery banks, calibrate MPPT charging profiles, upgrade lead-gel systems to high-efficiency LiFePO4 lithium batteries, and ensure 24/7 power availability.',
    specifications: [
      'Battery State of Health (SOH) & Impedance Diagnostic Testing',
      'Gel-to-Lithium Battery Retrofit & BMS Configuration',
      'Inverter Firmware Flash & Solar Input Voltage Calibration',
      'Emergency Backup Transfer Switch Testing',
    ],
    price_range: 'Custom Quote',
    is_active: true,
    display_order: 3,
    created_at: '2026-08-01T10:00:00Z',
  },
];
